-- Give me the top 3 products by revenue inside every category.
Select 
	CategoryName,
	ProductName,
	Revenue
From
(
Select 
	CategoryName,
	ProductName,
	Revenue,
	Row_Number() over (Partition by CategoryName order by Revenue DESC) as Rank
From 
	Categories C Inner Join 
(
Select
	P.CategoryID,
	P.ProductID,
	P.ProductName,
	Sum((OD.UnitPrice*OD.Quantity)*(1-(OD.Discount/100))) as Revenue
From 
	Products P Inner join OrderDetails OD on P.ProductID = OD.ProductID
Group by 
	P.categoryID,
	P.Productname,
	P.ProductID
) as T 	
on T.CategoryID = C.CategoryID
) as F
Where 
	Rank <= 3

--------------------------------------------------------------------------
-- Find the top 10 customers by total revenue, and show their rank
Select * from OrderDetails
Select * From Customers
Select * from Orders

Select 
	Rank,
	CustomerID,
	CustomerName,
	Revenue
From
(
Select 
	CustomerID,
	CustomerName,
	Revenue,
	Rank() over (order by Revenue DESC) as Rank
From
(
Select 
	C.CustomerID,
	C.CustomerName,
	Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100)) as Revenue
From 
	Customers C inner Join Orders O on C.CustomerID = O.CustomerID
	inner join OrderDetails OD on O.OrderID = OD.OrderID
Group by 
	C.CustomerName,
	C.CustomerID
) as T
) as F
where
	Rank <= 10


--------------------------------------------------------------------
-- Show monthly revenue and the difference from the previous month.

Select
	Format(Month_Year,'MMMM yyyy') as Month_Year,
	Revenue,
	Lag(Revenue) over (order by Month_Year) as Previous_Month_Revenue,
	(Revenue - Lag(Revenue) over (Order by Month_Year) ) as Difference
From
(
Select
	Month_Year,
	Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100)) as Revenue
From OrderDetails OD inner join 
(
Select
	OrderID,
	DateFromParts(Year(OrderDate),
				  Month(OrderDate),
				  1) as Month_Year
From 
	Orders 
	) as T
on T.OrderID = OD.OrderID
Group by 
	Month_Year
) as F

------------------------------------------------------------
-- For each month, show the current month's revenue and the next month's revenue
Select
	Format(Month_Year,'MMMM yyyy') as Month_Year,
	Revenue,
	Lag(Revenue) over (order by Month_Year) as Previous_Month_Revenue,
	Lead(Revenue) over (order by Month_Year) as Next_Month_Revenue,
	(Revenue - Lag(Revenue) over (Order by Month_Year) ) as Difference
From
(
Select
	Month_Year,
	Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100)) as Revenue
From OrderDetails OD inner join 
(
Select
	OrderID,
	DateFromParts(Year(OrderDate),
				  Month(OrderDate),
				  1) as Month_Year
From 
	Orders 
	) as T
on T.OrderID = OD.OrderID
Group by 
	Month_Year
) as F

-------------------------------------------------------
-- Find products that are inactive but were sold
Select * From Products
Select * From Orders
ProductID
ProductName
ProductStatus
NumberOfOrders
Revenue
Select
	P.ProductID,
	P.ProductName,
	P.ProductStatus,
	Count(OD.ProductID) as NumberofOrders,
	Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100)) as Revenue
From	
	Products P inner join OrderDetails OD on P.ProductID = OD.ProductID
Group by 
	P.ProductID,
	P.ProductName,
	P.ProductStatus
Having
	P.ProductStatus <> 'Active'

---------------------------------------------------------------------------
--  Duplicate Customers
Select 
	CustomerName,
	Email,
	Phone,
	Count(*) as DuplicateCount
From 
	Customers
Group by 
	CustomerName,
	Email,
	Phone
Having 
	Count(*) > 1


------------------------------------------------------------------------------ 
-- Find customers who are missing either Email OR Phone.
Select 
	CustomerID,
	CustomerName,
	Email,
	Phone
From 
	Customers
Where
	Email is Null or Phone is Null


------------------------------------------------------------------
-- Find the total revenue generated by each OrderStatus
	Select 
		O.OrderStatus,
		Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100.0)) as Revenue
	From 
		Orders O inner join OrderDetails OD on O.OrderID = OD.OrderID
	Group by 
		O.OrderStatus

--------------------------------------------------------------------
-- Find products where the average selling price in OrderDetails is different from the current. To check on which margin Products are Sold	
Select 
	P.ProductID,
	P.ProductName,
	P.UnitPrice,
	AvgSellPrice
From 
	Products P inner join 
(
Select 
	ProductID,	
	AVG(UnitPrice) as AvgSellPrice
From 
	OrderDetails
Group by 
	ProductID
) as T
on T.ProductID = P.ProductID

----------------------------------------------------------
-- Find orders where the same ProductID appears more than once within the same OrderID.
Select
	ProductID,
	OrderID,
	Count(*) as Duplicates
From 
	OrderDetails
Group by
	ProductID,
	OrderID
Having 
	Count(*) > 1

------------------------------------------------------------
-- Find customers who have placed more than 10 orders.
Select 
	CustomerID,
	CustomerName,
	Revenue,
	CountofOrders
From 
(
Select
	C.CustomerID,
	C.CustomerName,
	Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100.0)) as Revenue,
	Count(Distinct OD.OrderID) as CountofOrders
From 
	OrderDetails OD inner join Orders O on OD.OrderID = O.OrderID
	inner join Customers C on C.CustomerID = O.CustomerID
Group by 
	C.CustomerID,
	C.CustomerName
) as T
Where
	CountofOrders > 10 
Order by 
	Revenue DESC


---------------------------------------------------------------
-- NovaMart wants to classify customers based on their total revenue:
Select * from Customers
Select * from Orders
Select * from OrderDetails
Select 
	CustomerID,
	CustomerName,
	TotalRevenue,
	Case
	When TotalRevenue >= 1700000 then 'High Value'
	When TotalRevenue >= 900000 then 'Medium Value'
	Else 'Low Value' END
	as CustomerSegment
From 
(
Select 
	C.CustomerID,
	C.CustomerName,
	Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100.0)) as TotalRevenue
From 
	Customers C inner join Orders O on C.CustomerID = O.CustomerID
	inner join OrderDetails OD on OD.OrderID = O.OrderID
Group by 
	C.CustomerID,
	C.CustomerName
	) as T


----------------------------------------------------------------

Select 
	CustomerID,
	CustomerName,
	Email,
	Phone,
	Case 
	When Email is null and Phone is Null then 'Email,Phone is Null'
	When Email  is Null then 'Email is Null'
	When Phone  is Null then 'Phone is Null'
	Else 'Complete'
	END as DataQualityStatus
From 
	Customers

-----------------------------------------------------------------
-- DataQualityIssue -- IssueCount -- Combined
Select 
	'Missing Email' as DataQualityIssue,
	Count(*) as IssueCount
From 
	Customers 
Where 
	Email is Null

Union all 

Select 
	'Missing Phone' as DataQualityIssue,
	Count(*) as IssueCount
From 
	Customers 
Where 
	Phone is Null

Union all 
Select 
	'Duplicate Customers' as DataQualityIssue,
	Count(*) as IssueCount
	From
	(
	Select 
		CustomerName,
		Email,
		Phone
	From 
		Customers
	Group by 
		CustomerName,
		Email,
		Phone
	Having 
		Count(*)-1 >= 1
		) as Duplicates

Union all
Select 
	'InactiveProductSold' as DataQualityIssue,
	Count(*) as IssueCount
	From
	(
Select
	P.ProductID,
	P.ProductName,
	P.ProductStatus,
	Count(OD.ProductID) as NumberofOrders,
	Sum((OD.Quantity*OD.UnitPrice)*(1-OD.Discount/100)) as Revenue
From	
	Products P inner join OrderDetails OD on P.ProductID = OD.ProductID
Group by 
	P.ProductID,
	P.ProductName,
	P.ProductStatus
Having
	P.ProductStatus <> 'Active'
	) as Inactive

Union all 
Select 
	'DuplicateOrderDetails' as DataQualityIssue,
	Count(*) as IssueCount
From
(
Select 
	ProductID,
	OrderID,
	Duplicates-1 as Duplicate
From
(
Select
	ProductID,
	OrderID,
	Count(*) as Duplicates
From 
	OrderDetails
Group by
	ProductID,
	OrderID
	) as T
Where
	(Duplicates-1) >= 1
	) as DuplicateOrders